### ISSUE TITLE
merkle proof

### ISSUE THREAD

**Issue by zkfarmoor** [kocaemre/zkClaim#3]
Hello, thank you for providing this code. Would you happen to have the script for building the merkle tree and generating the merkleproof for an address? I am assuming you use the dataset provided by zksync here: https://github.com/ZKsync-Association/zknation-data/blob/main/eligibility_list.csv

This is the latest ZkMerkleDistributor contract: https://era.zksync.network/address/0x66fd4fc8fa52c9bec2aba368047a0b27e24ecfe4#code

Thank you for your help

**Comment by zkfarmoor** [comment]
nevermind, I found it while inspecting the network request

**Comment by kocaemre** [comment]
Sorry for late response. 

Enter : https://claim.zknation.io/
Then click left click-inspect select network. Then reload the page. Find starting with "eligi..". Click. Then enter response.  You will find index,token amount and merkleProofs
